# Generated by Django 5.2.2 on 2025-06-06 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('diet_json', models.JSONField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"public"."user_diet"',
            },
        ),
    ]
