# Generated by Django 5.2.2 on 2025-06-06 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('date', models.DateField(null=True)),
                ('total_proteins', models.IntegerField(null=True)),
                ('total_fats', models.IntegerField(null=True)),
                ('total_carbs', models.IntegerField(null=True)),
                ('total_kcals', models.IntegerField(null=True)),
                ('kcals_goal', models.IntegerField(null=True)),
                ('proteins_goal', models.IntegerField(null=True)),
                ('fats_goal', models.IntegerField(null=True)),
                ('carbs_goal', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"public"."user_dailyprogress"',
            },
        ),
    ]
