# Generated by Django 5.2.2 on 2025-06-06 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_userdailyprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('proteins_gr', models.IntegerField(null=True)),
                ('fats_gr', models.IntegerField(null=True)),
                ('carbs_gr', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"public"."user_meal"',
            },
        ),
    ]
