# Generated by Django 5.2.2 on 2025-06-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_usermeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyprogress',
            name='diet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diet.userdiet'),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='carbs_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='fats_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='proteins_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='total_kcals',
            field=models.IntegerField(null=True),
        ),
    ]
