# Generated by Django 5.2.2 on 2025-06-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_userdailyprogress_diet_userdiet_carbs_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
