# Generated by Django 5.2.2 on 2025-06-08 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_usermeal_date_usermeal_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diet.usermeal')),
            ],
            options={
                'db_table': '"public"."user_mealingredient"',
            },
        ),
    ]
