# Generated by Django 5.2.2 on 2025-06-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_usermealingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('fats_g', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('proteins_g', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': '"public"."food_macro"',
            },
        ),
    ]
