# Generated by Django 5.2.2 on 2025-06-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_foodmacro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': '"public"."food_category"',
            },
        ),
    ]
