# Generated by Django 5.2.2 on 2025-06-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_foodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmacro',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diet.foodcategory'),
        ),
    ]
