# Generated by Django 5.2.2 on 2025-06-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_foodmacro_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmacro',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
