# Generated by Django 5.2.2 on 2025-06-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_foodmacro_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmacro',
            name='grams_per_unit',
            field=models.IntegerField(null=True),
        ),
    ]
