# Generated by Django 5.2.2 on 2025-06-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0011_foodmacro_grams_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyprogress',
            name='carbs_goal',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdailyprogress',
            name='fats_goal',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdailyprogress',
            name='kcals_goal',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdailyprogress',
            name='proteins_goal',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdailyprogress',
            name='total_carbs',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdailyprogress',
            name='total_fats',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdailyprogress',
            name='total_kcals',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdailyprogress',
            name='total_proteins',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdiet',
            name='carbs_g',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdiet',
            name='fats_g',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdiet',
            name='proteins_g',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userdiet',
            name='total_kcals',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='carbs_gr',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='fats_gr',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='proteins_gr',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
