# Generated by Django 5.2.2 on 2025-06-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0012_alter_userdailyprogress_carbs_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=120)),
                ('time', models.TimeField()),
                ('total_proteins', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_fats', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_carbs', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('diet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diet.userdiet')),
            ],
            options={
                'db_table': '"public"."user_dietmeal"',
            },
        ),
        migrations.CreateModel(
            name='UserDietMealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=120)),
                ('total_proteins', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_fats', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_carbs', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=120)),
                ('diet_meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diet.userdietmeal')),
            ],
            options={
                'db_table': '"public"."user_diet_mealcomponent"',
            },
        ),
        migrations.CreateModel(
            name='MealComponentSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('meal_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='substitutions_as_main', to='diet.userdietmealcomponent')),
                ('substitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='substitutions_as_alternative', to='diet.userdietmealcomponent')),
            ],
            options={
                'db_table': '"public"."meal_component_substitution"',
            },
        ),
    ]
