# Generated by Django 5.2.2 on 2025-06-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutExerciseSessionSet',
            new_name='WorkoutSessionExerciseSet',
        ),
        migrations.AlterModelTable(
            name='workoutsessionexerciseset',
            table='"workout_session_exerciseset"',
        ),
    ]
