# Generated by Django 5.2.2 on 2025-06-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_workoutexercisesessionset_workoutsessionexerciseset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='series',
            new_name='sets',
        ),
    ]
