# Generated by Django 5.2.2 on 2025-06-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_rename_series_workoutexercise_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='order',
            new_name='exercise_order',
        ),
    ]
