# Generated by Django 5.2.2 on 2025-06-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': '"public"."exercise_equipment"',
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': '"public"."exercise_type"',
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': '"public"."muscle_group"',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exerciseequipment')),
                ('exercise_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercisetype')),
                ('muscle_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.musclegroup')),
            ],
            options={
                'db_table': '"public"."exercise"',
            },
        ),
    ]
