# Generated by Django 5.2.2 on 2025-06-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_image_url'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.team'),
        ),
    ]
