# Generated by Django 5.2.2 on 2025-06-17 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('week_day', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"public"."workout"',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('series', models.IntegerField(null=True)),
                ('min_reps', models.IntegerField(null=True)),
                ('max_reps', models.IntegerField(null=True)),
                ('observations', models.TextField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercise')),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workout.workout')),
            ],
            options={
                'db_table': '"public"."workout_exercise"',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('workout_date', models.DateField(null=True)),
                ('started_datm', models.DateTimeField(null=True)),
                ('finished_datm', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('total_kgs', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workout.workout')),
            ],
            options={
                'db_table': '"public"."workout_session"',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('total_kgs', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercise')),
                ('workout_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workout.workoutsession')),
            ],
            options={
                'db_table': '"public"."workout_session_exercise"',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSessionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('set_number', models.IntegerField(null=True)),
                ('reps_done', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('rest_time', models.TimeField(null=True)),
                ('observations', models.TextField(null=True)),
                ('reps_in_reserve', models.IntegerField(null=True)),
                ('session_exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workout.workoutsessionexercise')),
            ],
            options={
                'db_table': '"public"."workout_exercise_sessionset"',
            },
        ),
    ]
