# Generated by Django 5.2.2 on 2025-06-06 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('hash', models.UUIDField(default=uuid.uuid4, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
