# Generated by Django 5.2.2 on 2025-06-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_first_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
