# Generated by Django 5.2.2 on 2025-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datm_insert', models.DateTimeField(null=True)),
                ('datm_update', models.DateTimeField(null=True)),
                ('datm_delete', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('base_prompt', models.TextField(null=True)),
                ('chat_name', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': '"public"."ai_roles"',
            },
        ),
    ]
